#!/usr/bin/env python3
#Create a list containing three items
my_list = ["192.168.05", 5060, "UP" ]
challenge_list = [ 5060, "80", 55, "10.0.0.1", "10.209.30.1", "ssh"]



#display the first item in the lsit
print("The first item in the list (IP): " + my_list[0])

#display the second item in the list 
print("The second item in the list (port): " + str(my_list[1]))

#display the third item in the list
print("The last item in the list (state): " + my_list[2])

print(f"The first ip address is: {challenge_list[3]} and the second one is: {challenge_list[4]}") 

