#!/usr/bin/env python3

def main():

    user_input = input("Please enter an IPv4 IP address:")

    print("You told me the IPv4 address is:", user_input)
    

    user_input2 = input("What is the vendor name:")

    print("You told me the vendor name is:", user_input2)
main()
