#!/usr/bin/env python3

def main():
    round = 0
    answer= " "
    while round < 3 and answer != "brian":
        round += 1
        answer = input(("Finish the movie title, 'Monty Python\'s The Life of -----'\n")) 
        if answer == "brian":
            print("correct")
            break
        elif round==3:
            print("Sorry, the answer was Brian.")
            break
        elif answer == "shrubbery":
            print("You gave the super secret answer!")
            break
        else:
            print("Sorry! Try again!")
main()
